<?php

    // --------------------------------------------------
    // DO NOT EDIT THIS FILE
    // --------------------------------------------------

    define ( 'FRAME_ROOT_PATH', __DIR__ );

    define ( 'FRAME_CORE_PATH', FRAME_ROOT_PATH . '/core' );

    define ( 'FRAME_SRC_PATH', FRAME_ROOT_PATH . '/src' );

    define ( 'FRAME_CONFIG_PATH', FRAME_SRC_PATH . '/Config' );

    define ( 'FRAME_MANAGER_PATH', FRAME_SRC_PATH . '/Manager' );

    define ( 'FRAME_ENTITY_PATH', FRAME_SRC_PATH . '/Entity' );

    require FRAME_CORE_PATH . '/FrameLoader.php';
